# TODO NUKEM - PR Ticket Link Action
# Automatically adds ticket links to PR descriptions based on branch names
# https://github.com/jolution/todo-nukem

name: "TODO NUKEM PR Ticket Link"
description: "Automatically adds ticket links to PR descriptions based on branch names"
author: "jolution"

branding:
  icon: "link"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token for API access"
    required: true
    default: ${{ github.token }}
  hidePromotion:
    description: "Hide the 'via TODO NUKEM' promotion link"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Read ticketBaseUrl
      shell: bash
      run: |
        # Try .todonukem-local.json first (local override)
        if [ -f .todonukem-local.json ]; then
          TICKET_BASE_URL=$(jq -r '.ticketBaseUrl // empty' .todonukem-local.json)
          if [ -n "$TICKET_BASE_URL" ]; then
            echo "âœ… Using ticketBaseUrl from .todonukem-local.json"
            echo "TICKET_BASE_URL=$TICKET_BASE_URL" >> $GITHUB_ENV
            exit 0
          fi
        fi

        # Try .todonukem.json
        if [ -f .todonukem.json ]; then
          TICKET_BASE_URL=$(jq -r '.ticketBaseUrl // empty' .todonukem.json)
          if [ -n "$TICKET_BASE_URL" ]; then
            echo "âœ… Using ticketBaseUrl from .todonukem.json"
            echo "TICKET_BASE_URL=$TICKET_BASE_URL" >> $GITHUB_ENV
            exit 0
          fi
        fi

        # Fallback to package.json
        if [ -f package.json ]; then
          TICKET_BASE_URL=$(jq -r '.todonukem.ticketBaseUrl // empty' package.json)
          if [ -n "$TICKET_BASE_URL" ]; then
            echo "âœ… Using ticketBaseUrl from package.json"
            echo "TICKET_BASE_URL=$TICKET_BASE_URL" >> $GITHUB_ENV
            exit 0
          fi
        fi

        echo "âš ï¸ Warning: ticketBaseUrl not found in .todonukem-local.json, .todonukem.json or package.json"
        echo "Skipping ticket link addition. Configure ticketBaseUrl in one of these files to enable this feature."
        exit 0

    - name: Extract ticket number from branch
      if: env.TICKET_BASE_URL
      shell: bash
      run: |
        BRANCH_NAME="${GITHUB_HEAD_REF:-}"
        TICKET_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '[0-9]+' || true)
        if [ -z "$TICKET_NUMBER" ]; then
          echo "âš ï¸ No ticket number found in branch name"
          exit 0
        fi
        echo "ðŸŽ« Found ticket number: $TICKET_NUMBER"
        echo "TICKET_NUMBER=$TICKET_NUMBER" >> $GITHUB_ENV

    - name: Update PR body
      uses: actions/github-script@v7
      if: env.TICKET_BASE_URL && env.TICKET_NUMBER
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const pr_number = context.payload.pull_request.number;

          // Get current PR
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number
          });

          const current_body = pr.body || '';
          
          const hidePromotion = '${{ inputs.hidePromotion }}' === 'true';
          const promotion = hidePromotion ? '' : '\n\n*via [TODO NUKEM](https://github.com/jolution/todo-nukem)*';
          const ticket_link = `[ ðŸŽ« [${process.env.TICKET_NUMBER}](${process.env.TICKET_BASE_URL}${process.env.TICKET_NUMBER}) ]${promotion}`;

          // Append ticket link to existing description
          const new_body = current_body 
            ? `${current_body}\n\n---\n${ticket_link}`
            : ticket_link;

          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number,
            body: new_body
          });
