name: Issue report
description: Report any problem here
labels: [ "Status: Awaiting triage" ]
body:
  - type: markdown
    attributes:
      value: |
        * Before reporting a new issue please check and search in [List of existing issues](https://github.com/jolution/todo-nukem/issues?q=is%3Aissue) 
        * If still experiencing the issue, please provide as many details as possible below.
        * If you would like to contribute, please read the [contributions guide](https://github.com/jolution/.github/blob/main/CONTRIBUTING.md).
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What actual browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/jolution/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
